### ISSUE TITLE
[New Org]: 

### ISSUE THREAD

**Issue by chriscoad** [bbrewington/atlanta-data-community#1]
### Community Name

Atlanta Low Key Data Meetup

### Community Description

Low-key data meetups are an opportunity to come hangout with other practitioners with no vendor presentations, no sales, and no data collection. Come meet your data and analytics peers, share best practices, horror stories, and laughs in a casual environment.

### Link(s)

https://www.meetup.com/atlanta-low-key-data-meetup/

**Comment by bbrewington** [comment]
Added, thanks! (And not sure how I missed that one lol…I’m in it)
